version: '2'

services:
        db:
                image: mysql/mysql:5.7
                volumes:
                        - ./database/gestion_produit.sql:/docker-entrypoint-initdb.d/data.sql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_DATABASE: gestion_projet

        web:
                depends_on:
                        - db
                image: nimmis/apache-php5
                ports:
                        - "80:80"
                        - "443:443"
                restart: always
                volumes:
                        - /var/www/html/gestion

