version: '2'

services:
        db:
                image: mysql:5.7
                volumes:
                        - ./database/gestion_produit.sql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_DATABASE: gestion_projet

        web:
            build:
                context: ./PHP
            depends_on:
                - db
            image: nimmis/apache-php5
            ports:
                - "80:80"
                - "443:443"
            restart: always
            volumes:
                - ../www/:/var/www/html/gestion
                - ./PHP/conf.d/
        storage:
            image: minio/minio
            volumes:
                - ./minio-volume/:/export
            ports:
            - "9001:9000"
            environment:
                MINIO_ACCESS_KEY: admin
                MINIO_SECRET_KEY: minio_secret_key
            command: server /export
