version: '2'

services:
        db:
                image: mysql/mysql:5.7
                volumes:
                        - ./database/gestion_produit.sql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_DATABASE: gestion_projet

        web:
                build:
                        context: ./PHP
                depends_on:
                        - db
                image: 
                ports:
                        - "80:80"
                        - "443:443"
                restart: always
                volumes:
                        - ../www/:/var/www/html/gestion
                        - ./PHP/conf.d/

